"""empty message

Revision ID: 06ed814d7b97
Revises: 0e13d694597d
Create Date: 2020-04-04 23:00:33.286954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06ed814d7b97'
down_revision = '0e13d694597d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # If you are going to add a column with NOT NULL constraints and the table has already a data, follow this method.

    # Change first the nullable into True.
    op.add_column('todo', sa.Column('completed', sa.Boolean(), nullable=True))

    # Execute a SQL UPDATE statement.
    op.execute('UPDATE todo SET completed=False WHERE completed IS NULL;')

    # Alter the column contraints into NOT NULL.
    op.alter_column('todo', 'completed', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo', 'completed')
    # ### end Alembic commands ###
